"""add_order_status_column

Revision ID: 2dc1cf6208c1
Revises: 6c77569c30db
Create Date: 2026-03-01 18:08:54.715901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc1cf6208c1'
down_revision: Union[str, Sequence[str], None] = '6c77569c30db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # SQLite cannot add a NOT NULL column without a default to existing tables.
    # We add it as nullable with a server default, backfill, then it's effectively
    # always populated going forward.
    op.add_column(
        'orders',
        sa.Column('status', sa.String(length=20), nullable=True, server_default='pending')
    )
    # Backfill all existing rows
    op.execute("UPDATE orders SET status = 'pending' WHERE status IS NULL")
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
